import { Shield, Eye, Lock } from 'lucide-react'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import PageWrapper from '@/components/PageWrapper'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Read the Gridlett Privacy Policy. Learn how we handle your energy consumption telemetry, WhatsApp notifications, and account verification data.',
  alternates: {
    canonical: '/privacy',
  },
}

export default function PrivacyPage() {
  return (
    <main className="relative min-h-screen bg-brand-black text-brand-text overflow-hidden flex flex-col justify-between">
      {/* Background grid texture */}
      <div className="fixed inset-0 bg-grid-pattern opacity-30 pointer-events-none" />

      {/* Ambient background blobs */}
      <div className="fixed top-0 left-1/4 w-[500px] h-[500px] orb-blue pointer-events-none -translate-y-1/2 opacity-40" />
      <div className="fixed bottom-1/4 right-0 w-[450px] h-[450px] orb-emerald pointer-events-none translate-x-1/3 opacity-30" />

      {/* Header */}
      <Header />

      {/* Main Content Container */}
      <div className="relative z-10 flex-1 pt-32 pb-24 px-6 max-w-4xl mx-auto w-full">
        {/* Page Header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 text-xs font-semibold px-4 py-2 rounded-full mb-3"
            style={{ background: 'rgba(16,185,129,0.08)', border: '1px solid rgba(16,185,129,0.2)', color: '#34D399' }}>
            <Lock className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
            Privacy Center
          </div>
          <h1 className="font-display text-4xl md:text-5xl font-bold text-white">
            Privacy <span className="text-gradient-emerald">Policy</span>
          </h1>
          <p className="mt-4 text-brand-text max-w-lg mx-auto text-sm leading-relaxed">
            Last Updated: June 2026. Your privacy and energy security are our top priorities.
          </p>
        </div>

        {/* Privacy Document Body wrapped in Client Transition */}
        <PageWrapper>
          <div 
            className="glass-card rounded-3xl p-6 md:p-10 border border-brand-border/60 space-y-8 text-sm md:text-base leading-relaxed text-brand-text"
            style={{ background: 'rgba(21, 30, 46, 0.6)' }}
          >
            {/* Section 1 */}
            <section className="space-y-3">
              <h2 className="font-display text-lg font-bold text-white flex items-center gap-2">
                <Eye className="w-5 h-5 text-emerald-400" />
                1. Information We Collect
              </h2>
              <p>
                To provide the energy subscription billing and load limiting services, we collect:
              </p>
              <ul className="list-disc pl-5 space-y-1.5 text-sm">
                <li>**Account Details**: Name, email address, WhatsApp number, and password hash during registration.</li>
                <li>**Property Details**: Cluster codes, building/apartment numbers, and overall shared property parameters.</li>
                <li>**Energy Consumption Telemetry**: Real-time electrical usage metrics (kW power draw, cumulative energy consumption in kWh, and load-limit event counts) generated by the Smart Controller meter linked to your account.</li>
              </ul>
            </section>

            {/* Section 2 */}
            <section className="space-y-3">
              <h2 className="font-display text-lg font-bold text-white flex items-center gap-2">
                <Shield className="w-5 h-5 text-blue-400" />
                2. How We Use Your Data
              </h2>
              <p>
                We process your telemetry and personal details to:
              </p>
              <ul className="list-disc pl-5 space-y-1.5 text-sm">
                <li>Manage your monthly energy prepaid subscriptions.</li>
                <li>Verify accounts and send automated load violation notifications or billing receipts via **WhatsApp**.</li>
                <li>Perform remote load balancing, predictive hardware diagnostics, and grid stability optimization.</li>
              </ul>
            </section>

            {/* Section 3 */}
            <section className="space-y-3">
              <h2 className="font-display text-lg font-bold text-white flex items-center gap-2">
                <Lock className="w-5 h-5 text-emerald-400" />
                3. Data Retention & Sharing
              </h2>
              <p>
                Gridlett does not rent, sell, or disclose your energy metrics or personal data to third-party advertising brokers. 
              </p>
              <p>
                We share aggregated load data with your property partner (landlord or facility manager) only as necessary to resolve billing queries or hardware balancing issues. Gridlett retains billing and diagnostic data for the duration of your contract, plus a standard archiving period to comply with Nigerian corporate and financial reporting regulations.
              </p>
            </section>

            {/* Section 4 */}
            <section className="space-y-3">
              <h2 className="font-display text-lg font-bold text-white flex items-center gap-2">
                <Shield className="w-5 h-5 text-blue-400" />
                4. Data Protection & Security
              </h2>
              <p>
                All communication between our smart metering hardware, portal databases, and your browser is encrypted using industry-standard Transport Layer Security (TLS/SSL). Telemetry logs are stored in secure environments with restricted access.
              </p>
            </section>

            {/* Section 5 */}
            <section className="space-y-3">
              <h2 className="font-display text-lg font-bold text-white flex items-center gap-2">
                <Eye className="w-5 h-5 text-emerald-400" />
                5. Your Privacy Choices
              </h2>
              <p>
                You can access, modify, or download your historical usage reports and subscription details at any time through the customer portal. If you move out or cancel your subscription, you may request complete account erasure by writing to operations@gridlett.com.
              </p>
            </section>
          </div>
        </PageWrapper>
      </div>

      {/* Footer */}
      <Footer />
    </main>
  )
}
